name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - '3.8.x'
          - '3.9.x'
          - '3.10.x'
        os:
          - ubuntu-20.04
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    name: Python ${{ matrix.python-version }} test on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
        with:
          version: 1.3.2
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi
          poetry show
      - name: Run tests
        run: |
          poetry run pytest
        shell: bash
